name: CI/CD Pipeline

on: [push]

jobs:
  check:
       name: Debug file structure
       run: |
           pwd
           ls -la
           ls -la data/ || echo "data directory not found"
           ls -la files/ || echo "files directory not found"
      
 
  
  
  
  
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
            cd ./src
            python ViT.py
            sleep 5 
            pytest tests/test.py -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t Vision_Transformer .

      - name: Log in to Docker Hub (optional)
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to Docker Hub (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag Vision_Transformer ${{ secrets.DOCKER_HUB_USERNAME }}/first:transformer
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/first:transformer

